"""Add plan_id and subscription_id with named FKs

Revision ID: da3a52e3c5d6
Revises: 
Create Date: 2025-12-12 09:33:52.459267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da3a52e3c5d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ecocash_transaction_id', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint('uq_invoices_ecocash_transaction_id', ['ecocash_transaction_id'])
        batch_op.drop_column('hosted_invoice_url')
        batch_op.drop_column('stripe_invoice_id')
        batch_op.drop_column('pdf_url')

    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('phone_number_verified', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint('uq_payment_methods_phone_number', ['phone_number'])
        batch_op.drop_column('card_last4')
        batch_op.drop_column('bank_last4')
        batch_op.drop_column('card_exp_month')
        batch_op.drop_column('card_brand')
        batch_op.drop_column('stripe_payment_method_id')
        batch_op.drop_column('card_exp_year')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('type')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ecocash_transaction_id', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint('uq_payments_ecocash_transaction_id', ['ecocash_transaction_id'])
        batch_op.drop_column('stripe_charge_id')
        batch_op.drop_column('stripe_payment_intent_id')

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ecocash_monthly_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ecocash_annual_price', sa.Float(), nullable=True))
        batch_op.drop_column('stripe_price_id_monthly')
        batch_op.drop_column('stripe_price_id_annual')
        batch_op.drop_column('stripe_product_id')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('ecocash_transaction_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=True))
        batch_op.drop_index(batch_op.f('ix_subscriptions_stripe_customer_id'))
        batch_op.create_unique_constraint('uq_subscriptions_ecocash_transaction_id', ['ecocash_transaction_id'])
        batch_op.drop_column('stripe_customer_id')
        batch_op.drop_column('stripe_subscription_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ecocash_phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('current_subscription_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('subscription_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('subscription_ends_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('billing_email', sa.String(length=255), nullable=True))
        batch_op.create_foreign_key('fk_users_subscription_id', 'subscriptions', ['current_subscription_id'], ['id'])
        batch_op.create_foreign_key('fk_users_plan_id', 'plans', ['plan_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_plan_id', type_='foreignkey')
        batch_op.drop_constraint('fk_users_subscription_id', type_='foreignkey')
        batch_op.drop_column('billing_email')
        batch_op.drop_column('subscription_ends_at')
        batch_op.drop_column('subscription_status')
        batch_op.drop_column('current_subscription_id')
        batch_op.drop_column('ecocash_phone_number')
        batch_op.drop_column('plan_id')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_subscription_id', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('stripe_customer_id', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint('uq_subscriptions_ecocash_transaction_id', type_='unique')
        batch_op.create_index(batch_op.f('ix_subscriptions_stripe_customer_id'), ['stripe_customer_id'], unique=False)
        batch_op.drop_column('currency')
        batch_op.drop_column('ecocash_transaction_id')
        batch_op.drop_column('phone_number')

    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_product_id', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('stripe_price_id_annual', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('stripe_price_id_monthly', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('ecocash_annual_price')
        batch_op.drop_column('ecocash_monthly_price')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_payment_intent_id', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('stripe_charge_id', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint('uq_payments_ecocash_transaction_id', type_='unique')
        batch_op.drop_column('ecocash_transaction_id')

    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('bank_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('card_exp_year', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('stripe_payment_method_id', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('card_brand', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('card_exp_month', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('bank_last4', sa.VARCHAR(length=4), nullable=True))
        batch_op.add_column(sa.Column('card_last4', sa.VARCHAR(length=4), nullable=True))
        batch_op.drop_constraint('uq_payment_methods_phone_number', type_='unique')
        batch_op.drop_column('phone_number_verified')
        batch_op.drop_column('phone_number')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_url', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('stripe_invoice_id', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('hosted_invoice_url', sa.VARCHAR(length=500), nullable=True))
        batch_op.drop_constraint('uq_invoices_ecocash_transaction_id', type_='unique')
        batch_op.drop_column('ecocash_transaction_id')

    # ### end Alembic commands ###
